apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: newrelic-logging
  namespace: newrelic
  labels:
    k8s-app: newrelic-logging
    version: v1
    kubernetes.io/cluster-service: "true"
    name: newrelic-logging
spec:
  selector:
    matchLabels:
      name: newrelic-logging
  template:
    metadata:
      labels:
        k8s-app: newrelic-logging
        version: v1
        kubernetes.io/cluster-service: "true"
        name: newrelic-logging
    spec:
      serviceAccountName: newrelic-logging
      containers:
      - name: newrelic-logging
        env:
          - name: PATH
            value: "/var/log/containers/*_default_*.log"
          - name: NR_CATEGORY 
            value : "OpenShift"
          - name: NR_SOURCE 
            value : "ram-dev22"
          - name: CUSTOM_NGINX_CONTAINER 
            value : "custom-nginx"
          - name: NR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: ENDPOINT
            value : "https://log-api.newrelic.com/log/v1"
          - name: SOURCE
            value: "kubernetes"
          - name: LICENSE_KEY
            value: "xxxxxxx"
          - name: BUFFER_SIZE
            value: "2560000"
          - name: MAX_RECORDS
            value: "50000"
          - name: LOG_LEVEL
            value: "info"
        image: newrelic/newrelic-fluentbit-output:1.1.2
        command:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/fluent-bit.conf
          - -e
          - /fluent-bit/bin/out_newrelic.so
        securityContext:
          privileged: true

        resources:
          limits:
            cpu: 800m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
        - name: varlog
          mountPath: /var
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var
